"""Embeds the files from web/ as gzip byte arrays in include/web_assets.h.

Runs as a pre-script on every build. This keeps the web source a normal,
editable file while a single upload step is still enough - no separate
flashing of a file system that you are guaranteed to forget after an OTA.

Gzip instead of raw text for two reasons: it saves about two thirds of the
flash, and a C++ raw string would break the moment its delimiter sequence
appears in the HTML. A byte array cannot run into that.

PROGMEM is not needed on the ESP32 - the flash is mapped into the address
space, a const array lives in .rodata anyway and can be read normally.
"""

import gzip
import hashlib
import os
import textwrap

Import("env")   # noqa: F821  (provided by SCons)

PROJECT = env["PROJECT_DIR"]            # noqa: F821
SOURCES = {
    "INDEX_HTML": os.path.join(PROJECT, "web", "index.html"),
    "SETUP_HTML": os.path.join(PROJECT, "web", "setup.html"),
}
TARGET = os.path.join(PROJECT, "include", "web_assets.h")


def build_header():
    parts = [
        "// Generated by scripts/embed_web.py - do not edit by hand.\n",
        "// The source is the files in web/; changes there take effect on the next build.\n",
        "\n#pragma once\n\n#include <stddef.h>\n#include <stdint.h>\n\n",
    ]

    for symbol, path in SOURCES.items():
        with open(path, "rb") as f:
            raw = f.read()

        # mtime=0, so two builds of the same source produce byte-identical
        # output - otherwise the header changes on every build and forces a
        # full recompile.
        packed = gzip.compress(raw, compresslevel=9, mtime=0)
        etag = hashlib.sha1(raw).hexdigest()[:16]

        bytes_text = ", ".join("0x%02x" % b for b in packed)
        parts.append(
            "// %s: %d bytes raw, %d bytes packed\n" % (os.path.basename(path), len(raw), len(packed))
        )
        parts.append("static const uint8_t %s_GZ[] = {\n" % symbol)
        parts.append(textwrap.fill(bytes_text, 96, initial_indent="    ", subsequent_indent="    "))
        parts.append("\n};\n")
        parts.append("static const size_t %s_GZ_LEN = %d;\n" % (symbol, len(packed)))
        parts.append('static const char %s_ETAG[] = "%s";\n\n' % (symbol, etag))

    return "".join(parts)


def main():
    missing = [p for p in SOURCES.values() if not os.path.isfile(p)]
    if missing:
        raise SystemExit("embed_web: source file missing: " + ", ".join(missing))

    new = build_header()

    old = None
    if os.path.isfile(TARGET):
        with open(TARGET, "r", encoding="utf-8") as f:
            old = f.read()

    if old == new:
        return

    os.makedirs(os.path.dirname(TARGET), exist_ok=True)
    with open(TARGET, "w", encoding="utf-8", newline="\n") as f:
        f.write(new)
    print("embed_web: regenerated include/web_assets.h")


main()
